export const APPOINTMENT_BOOK_REQUEST = 'APPOINTMENT_BOOK_REQUEST';
export const APPOINTMENT_BOOK_SUCCESS = 'APPOINTMENT_BOOK_SUCCESS';
export const APPOINTMENT_BOOK_FAIL = 'APPOINTMENT_BOOK_FAIL';

export const APPOINTMENT_MY_REQUEST = 'APPOINTMENT_MY_REQUEST';
export const APPOINTMENT_MY_SUCCESS = 'APPOINTMENT_MY_SUCCESS';
export const APPOINTMENT_MY_FAIL = 'APPOINTMENT_MY_FAIL';